services:
  api:
    build: .
    image: cryto-trading-web-backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
